project:
  type: website

website:
  title: "Leslie's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://lesliemalave.github.io
      
format:
  html:
    theme: vapor
    css: styles.css

editor: visual

